### ISSUE TITLE
Resolution of Energy register

### ISSUE THREAD

**Issue by SkyumP** [cenobitedk/esphome_multical402#5]
Hi

the information I read from the energy register is in KWh with no decimals value. 

This is not a very good resolution when energy consumption is around 5-20 KWh in the summer period. 

In HA it gives this result in the energy dashboard:
![IMG_2118](https://github.com/cenobitedk/esphome_multical402/assets/86803989/ca6d15a9-2d4f-40e9-b303-6ba19f32e058)

But when I look at my suppliers statistics they have better resolution in my energy data:
![IMG_2117](https://github.com/cenobitedk/esphome_multical402/assets/86803989/6e39e556-422f-4b95-8637-ef91dd995751)

Therefore I assume that the data is available in the Multical but not stored in the Energy register…

Any ideas which register (if any) would store more detailed energy data?

**Comment by htvekov** [comment]
**EDIT: After some hours of testing it seems that the last 2 digits in my energy register doesn't have any significance and apparently are somewhat random (usually 00, 01 or 99). So the proposed solution below simply won't work IRL.
Perhaps the digits actually _have_ significance with your MultiCal 403 meter, as your register reports in kWh and not in MWh as my MultiCal 602 meter ?**




My Multical 602 delivers the energy register in MWh with 5 decimals precision. My initial, default ESPHome config returned the sensor value with 3 decimals -> 1 kWh resolution.

If you want better sensor resolution in HA, you need to change the number of decimals in ESPHome to 4 ( 0.1 kWh resolution ) or even 5 ( 0.01 kWh resolution ). Assuming that your Multical energy meter actually provides that kind of resolution ?

```yaml
# Multical Custom Sensors
- name: "Multical Energy"
  platform: template
  id: m_energy
  icon: "mdi:lightning-bolt"
  unit_of_measurement: MWh
  accuracy_decimals: 5
  state_class: "total_increasing"
  device_class: "energy"
```

```yaml
10:05:42 | [D] | [sensor:093] | 'Multical Energy': Sending state 157.09401 MWh with 5 decimals of accuracy
```

![image](https://github.com/cenobitedk/esphome_multical402/assets/45469813/0093070c-4335-4e3e-996e-d117a171bf27)
